# validate_annotations.py
# This program will make sure the annotations.json file generated by main.py
# is accurate, contains all categories.

import json

with open("annotations.json", "r") as f:
    annotations = json.load(f)

valid_count = 0
for a in annotations:
    valid = True
    for cat in ["story", "suspense", "curiosity", "surprise"]:
        if "story" not in annotations[a]:
            print(f"Passage ID {a}: no {cat} annotation!")
            valid = False
    if valid:
        valid_count += 1

print(f"{valid_count}/{len(annotations)} were valid.")
